const express = require('express');
const router = express.Router();
const { protect } = require('../middleware/authMiddleware');

// @desc    Generate AI response (integrates with Python PyTorch service)
// @route   POST /api/ai/generate
// @access  Private
router.post('/generate', protect, async (req, res) => {
  try {
    const { prompt, model } = req.body;

    if (!prompt) {
      return res.status(400).json({ success: false, message: 'Prompt is required' });
    }

    // AI Model Execution / Neural Reasoner v4.0 PyTorch Hook
    const selectedModel = model || 'Mathiyon Neural v4.0';

    let responseText = `[Mathiyon ${selectedModel}] Processed prompt: "${prompt}". Generated neural reasoning graph with high confidence score.`;

    if (prompt.toLowerCase().includes('react') || prompt.toLowerCase().includes('code')) {
      responseText = `\`\`\`tsx\n// Generated by ${selectedModel}\nimport React from 'react';\n\nexport const MathiyonCard = () => {\n  return (\n    <div className="p-6 rounded-2xl bg-[#0e0c1c] text-white border border-rose-500/30 shadow-glow-md">\n      <h3 className="text-lg font-bold">Mathiyon AI Neural Output</h3>\n    </div>\n  );\n};\n\`\`\``;
    }

    return res.json({
      success: true,
      model: selectedModel,
      prompt,
      response: responseText,
      timestamp: new Date().toISOString(),
    });
  } catch (error) {
    console.error('AI Route Error:', error);
    res.status(500).json({ success: false, message: 'AI model generation failed' });
  }
});

module.exports = router;
